discoveryregistry/discovery_register.go
discoveryregistry/zookeeper/zk.go

feat: change close function to interface Adapting for Kubernetes

---

utils/utils_v2.go
utils/utils_v2_test.go

feat: add StructFieldNotNilReplace

---

utils/utils_v2.go
utils/utils_v2_test.go

fix: fix the StructFieldNotNilReplace function

---

discoveryregistry/discovery_register.go
discoveryregistry/zookeeper/discover.go

feature:add interface get msggateway host by hash method

---

discoveryregistry/zookeeper/zk.go

update zk.go new client

---

log/zap.go

fix: limit log level to avoid gc alloc memory.

---

discoveryregistry/zookeeper/zk.go

fix: fix the zk tips

---

utils/utils_v2.go

optimization: slice sub.

---

errs/code.go
errs/predefine.go
mw/rpc_client_interceptor.go
mw/rpc_server_interceptor.go
utils/utils_v2.go

feat: add msg gateway error.

---

component/component.go
mgoutil/mongo.go

fix: update the component check logic

---

.github/code-language-detector.yml
.github/workflows/code-language-detector.yml

<br>
/kind feature
"A GitHub Action for detecting specified languages (e.g., Chinese or Japanese) in comments within code files across multiple programming languages (YAML, Go, Java, Rust). Ideal for projects aiming to adhere to internationalization standards or maintain language-specific coding guidelines."
+ [https://github.com/marketplace/actions/code-language-detector](https://github.com/marketplace/actions/code-language-detector)

create code language detector file

---

checker/check_test.go

add check_test.go file

---

db/redisutil/verify.go

fix panic in redis cluster mode.

---

apiresp/resp_test.go
go.mod
go.sum

Fixes   resolve uncurrent implement in tools.

refactor:rename pkg name to solve go mod error.

---

mw/replace_nil.go
mw/replace_nil_test.go
mw/rpc_server_interceptor.go

feat: replace nil

---

a2r/api2rpc.go
a2r/option.go
mw/replace_nil.go
mw/replace_nil_test.go
mw/rpc_server_interceptor.go
utils/mageutil/sys.go

Fixes #
Fix： replace nil in api

Fix replace nil

---

s3/cont/controller.go
s3/minio/minio.go
s3/minio/thumbnail.go
s3/s3.go

[Fixes #](feat: implement getthumbnail interface.)

feat: implement getthumbnail interface.

---

s3/minio/minio.go

implement correct get thumbnail size.

implement correct get thumbnail size

---

s3/minio/minio.go

[fix uncorrect getObjectImageInfo implement.](https://github.com/openimsdk/tools/commit/8698a50a44b6b5fb76751b6cf7dea84de5a22fdb)

fix uncorrect getObjectImageInfo implement.

---

s3/minio/image.go
s3/minio/minio.go

add getResizeImageSize function in minio

add getResizeImageSize function in minio

---

s3/minio/minio.go

refactor uncorrect getSIze implement.

refactor uncorrect getSIze implement.

---

s3/minio/image.go
s3/minio/minio.go

update getResizeImageSize implement.

update getResizeImageSize implement.

---

s3/minio/image.go
s3/minio/minio.go

fix thumbnailResize implement.

fix thumbnailResize implement.

---

s3/minio/image.go
s3/minio/minio.go

fix uncorrect implement in ResizeImage.

fix uncorrect implement in ResizeImage.

---

log/sql_logger.go

fix: add log kv args in sql logger.

fix: add log kv args in sql logger.

---

log/sql_logger.go

refactor: update sqlLogger implement with have err args.

refactor: update sqlLogger implement with have err args.

---

log/sql_logger.go

refactor: optimize error method implement in sqlLogger.

refactor: optimize error method implement in sqlLogger.

---

utils/datautil/datautil.go
utils/datautil/datautil_test.go

feature: slice sub

---

log/zap.go

feat: implement rpc log format

feat: implement rpc log format

---

log/zap.go

fix uncorrect index out.

---

go.mod
go.sum
s3/minio/image.go
s3/minio/thumbnail.go

feat: pic upload

---

utils/datautil/datautil.go

feat: slice copy

---

utils/stringutil/strings.go
utils/stringutil/strings_test.go

Fixes #
feat: CamelCaseToSpaceSeparated

feat: CamelCaseToSpaceSeparated

---

utils/stringutil/strings.go

feat: change first

---

utils/formatutil/format.go
utils/formatutil/format_test.go

feat: process bar.

---

utils/formatutil/format.go

fix: process bar.

---

mq/memamq/queue.go

feat: add push wait

---

utils/datautil/datautil.go

feat: shuffleSlice

---

log/zap.go
log/zap_test.go

feat: update sdk log.

---

log/zap.go
log/zap_test.go

fix: update new logger logic.

---

log/color.go
log/zap.go
log/zap_test.go

fix: log lose filepath.

---

utils/formatutil/format.go

Fixes #
fix: bar length print panic

fix: bar length print panic

---

mw/rpc_client_interceptor.go

fix: rpc log print

---

go.mod
go.sum
s3/minio/thumbnail.go

Fixes #
fix: thumbnail gen. Remove cgo package

fix: thumbnail gen. Remove cgo package

---

db/cacheutil/cache.go

feat: cache

---

utils/datautil/datautil.go

feat: map to slice

---

utils/datautil/datautil.go

fix: map to slice

---

utils/datautil/datautil.go

feat: contains

---

log/zap.go

…ndle the crash caused by the implementation
Fixes #

fix: implement the fmt.Stringer interface. when it is nil, it will handle the crash caused by the implementation

---

utils/stringutil/strings.go

Fixes #
feat: is alpha or numeric

feat: is alpha or numeric

---

utils/stringutil/strings.go

feat: check email

---

mw/errstack.go
mw/gin.go
mw/rpc_client_interceptor.go

feat: panic log

---

mw/gin.go

fix: GenPanicErr

---

mw/rpc_client_interceptor.go

fix: rpc err

---

discovery/etcd/etcd.go
discovery/kubernetes/kubernetes.go

fix: revert getConn.

---

mq/kafka/verify.go

build: implement kafka health check.

---

apiresp/gin.go

feat: gin err

---

apiresp/gin.go

revert: gin err

---

tokenverify/jwt_token.go

Fixes #
fix: jwt parse token err return

fix: jwt parse token err return

---

tokenverify/jwt_token.go

Fixes #
Add a lead time for the token's issuance time.

fix: Add a lead time for the token's issuance time.

---

s3/minio/minio.go

fix: update reqParams to support UTF-8

---

utils/runtimeenv/runtime.go

feat: add runtime env checker method.

---

discovery/zookeeper/log.go

fix: log loss method.

---

discovery/etcd/etcd.go
utils/network/ip.go

feat: ip && etcd

---

errs/stack.go
log/logger.go
log/zap.go
mw/errstack.go
mw/gin.go
mw/rpc_client_interceptor.go

feat: log.ZPanic

---

discovery/zookeeper/log.go

fix: zk log

---

discovery/kubernetes/kubernetes.go

fix: improve discovery implement.

---

db/mongoutil/verify.go
discovery/kubernetes/kubernetes.go

fix: improve error wrap.

---

a2r/call_v2.go

feat: call rpc v2

---

db/mongoutil/verify.go
discovery/etcd/etcd.go
discovery/kubernetes/kubernetes.go

build: improve discovery Opts check

---

discovery/etcd/etcd.go
discovery/kubernetes/kubernetes.go

fix: revert checkOpts.

---

s3/minio/minio.go
s3/minio/thumbnail.go

feat: Optimize minio's DeleteObject

---

mw/rpc_server_interceptor.go

feat: panic resp is success

---

go.mod
log/zap.go
mw/rpc_client_interceptor.go
mw/rpc_server_interceptor.go

feat: optimize log out

---

discovery/etcd/etcd.go

fix: etcd conn

---

log/zap.go

feat: log time.Duration format

---

apiresp/resp.go

fix: api error info

---

apiresp/resp.go
log/zap.go

fix: modify the panic level

---

db/redisutil/redis.go
mw/rpc_client_interceptor.go

fix: rpc to error code

---

log/simplify.go

fix: add simplify slice type

---

s3/oss/oss.go

fix: oss no longer supports setting response-content-type

---

db/mongoutil/util.go

feat: add InsertOne

---

queue/bound/bounded_queue.go
queue/task/options.go
queue/task/strategy.go
queue/task/task_queue_manager.go

Feat queue

---

errs/predefine.go

feat: add new error code.

---

utils/httputil/http_client.go

feat: NewHTTPClientWithClient

---

s3/kodo/kodo.go

fix: s3 kodo

---

discovery/zookeeper/log.go
log/async_test.go
log/logger.go
log/zap.go

feat: log support async

---

db/redisutil/redis.go
s3/oss/oss.go
xtls/tls.go

feat: support redis tls

---

discovery/discovery_register.go
discovery/etcd/etcd.go
discovery/kubernetes/kubernetes.go
discovery/standalone/kv.go
discovery/zookeeper/zk.go

fix: get Key with prefix

---

discovery/kubernetes/kubernetes.go

fix: k8s discovery

---

db/redisutil/redis.go

feat: support redis sentinel mode.

---

db/mongoutil/mongo.go

feat: support mongo replicaset.

---

db/mongoutil/mongo.go
db/redisutil/redis.go

fix: update correct tags.

---

mq/kafka/mq_consumer_group.go
mq/kafka/msg.go
mq/mq.go
mq/simmq/memory.go
mq/simmq/msg.go

feat: optimize mq encapsulation

---

log/async_test.go
log/zap.go

build: turn off AsyncWrite in logger.
